services:
  - type: web
    name: pro-media-downloader
    env: python
    buildCommand: pip install -r requirements.txt && apt-get update && apt-get install -y ffmpeg
    startCommand: python bot.py
    envVars:
      - key: PORT
        value: 10000
      - key: BOT_TOKEN
        sync: false
      - key: ADMIN_IDS
        value: 6836865426
